### ISSUE TITLE
通过home brew 分别安装了rancher-cli 和kubectl，插件检测不到版本，操作系统是Mac OS

### ISSUE THREAD

**Issue by wholon** [threefish/Rancher-plugins#1]
<img width="353" alt="image" src="https://github.com/threefish/Rancher-plugins/assets/55683600/eef7a2aa-4fd3-4279-9cd2-54796a06d361">
<img width="761" alt="image" src="https://github.com/threefish/Rancher-plugins/assets/55683600/5282aa1c-2182-4625-b429-0b1396c80deb">

**Comment by threefish** [comment]
我没有mac环境，让我想想怎么处理

**Comment by wholon** [comment]
好的，辛苦

**Comment by wholon** [comment]
咋样了，大佬

**Comment by twoicewoo** [comment]
这个问题解决了吗？

**Comment by threefish** [comment]
我尝试装mac虚拟机，没成功。你加我qq联系吧306955302&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nil ***@***.***&gt;; 
发送时间: 2023年6月19日(星期一) 上午10:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [threefish/Rancher-plugins] 通过home brew 分别安装了rancher-cli 和kubectl，插件检测不到版本，操作系统是Mac OS (Issue #1)





 
这个问题解决了吗？
 
&mdash;

**Comment by HaloTT** [comment]
我也是这个问题
![image](https://github.com/threefish/Rancher-plugins/assets/30413147/bdd86ae2-341e-472d-b1e2-53eb8aff0ceb)
![image](https://github.com/threefish/Rancher-plugins/assets/30413147/c521f949-1912-430e-8553-a2573be8df85)
<img width="456" alt="image" src="https://github.com/threefish/Rancher-plugins/assets/30413147/93dc2b2e-750c-429c-8e27-200cca78a2c6">

**Comment by threefish** [comment]
> 306955302

加我qq详聊

**Comment by threefish** [comment]
我增加一个配置选项，可执行文件的绝对路径，可以自己选择rancher及kubectl可执行文件的目录。[新插件版本下载地址](https://plugins.jetbrains.com/plugin/19316-rancher/versions/stable/356178)

**Comment by HaloTT** [comment]
> 我增加一个配置选项，可执行文件的绝对路径，可以自己选择rancher及kubectl可执行文件的目录。[新插件版本下载地址](https://plugins.jetbrains.com/plugin/19316-rancher/versions/stable/356178)

<img width="672" alt="image" src="https://github.com/threefish/Rancher-plugins/assets/30413147/20df0742-f006-4794-9e9c-a0917c30fbad">
还是有问题

**Comment by threefish** [comment]
> > 我增加一个配置选项，可执行文件的绝对路径，可以自己选择rancher及kubectl可执行文件的目录。[新插件版本下载地址](https://plugins.jetbrains.com/plugin/19316-rancher/versions/stable/356178)
> 
> <img alt="image" width="672" src="https://user-images.githubusercontent.com/30413147/251052665-20df0742-f006-4794-9e9c-a0917c30fbad.png"> 还是有问题
你的rancher服务端的版本是多少？

**Comment by HaloTT** [comment]
> > > 我增加一个配置选项，可执行文件的绝对路径，可以自己选择rancher及kubectl可执行文件的目录。[新插件版本下载地址](https://plugins.jetbrains.com/plugin/19316-rancher/versions/stable/356178)
> > 
> > 
> > <img alt="image" width="672" src="https://user-images.githubusercontent.com/30413147/251052665-20df0742-f006-4794-9e9c-a0917c30fbad.png"> 还是有问题
> > 你的rancher服务端的版本是多少？

应该是2.7

**Comment by HaloTT** [comment]
<img width="817" alt="image" src="https://github.com/threefish/Rancher-plugins/assets/30413147/c0566218-5972-41fd-be19-dad34f810958">直接访问地址是有相应的

**Comment by threefish** [comment]
> > > > 我增加一个配置选项，可执行文件的绝对路径，可以自己选择rancher及kubectl可执行文件的目录。[新插件版本下载地址](https://plugins.jetbrains.com/plugin/19316-rancher/versions/stable/356178)
> > > 
> > > 
> > > <img alt="image" width="672" src="https://user-images.githubusercontent.com/30413147/251052665-20df0742-f006-4794-9e9c-a0917c30fbad.png"> 还是有问题
> > > 你的rancher服务端的版本是多少？
> 
> 应该是2.7

我现在的是2.5.15，我先试试高版本的

**Comment by HaloTT** [comment]
> 

<img width="460" alt="image" src="https://github.com/threefish/Rancher-plugins/assets/30413147/11e74536-8bbc-42a5-8e4e-7a74ce7270af">
<img width="321" alt="image" src="https://github.com/threefish/Rancher-plugins/assets/30413147/460a5e12-a2e7-4e88-903d-961e1a941959">
不知道是不是我客户端和服务端版本不一样导致的，brew install 下载的默认就是2.6.11

**Comment by threefish** [comment]
> > 
> 
> <img alt="image" width="460" src="https://user-images.githubusercontent.com/30413147/251057998-11e74536-8bbc-42a5-8e4e-7a74ce7270af.png"> <img alt="image" width="321" src="https://user-images.githubusercontent.com/30413147/251058042-460a5e12-a2e7-4e88-903d-961e1a941959.png"> 不知道是不是我客户端和服务端版本不一样导致的，brew install 下载的默认就是2.6.11

没关系，我已经解决这个问题了，我再完善的测试下

**Comment by threefish** [comment]
https://plugins.jetbrains.com/plugin/19316-rancher/versions/stable/356632 已发布

**Comment by HaloTT** [comment]
> https://plugins.jetbrains.com/plugin/19316-rancher/versions/stable/356632 已发布

![image](https://github.com/threefish/Rancher-plugins/assets/30413147/d5b8f05d-9f7f-4611-9b7d-cdb151818c07)
地址配置成功，但是打开失败了，我的kubectl是使用docker for desktop启用k8s安装上的，不知道是不是和这个有关系

**Comment by threefish** [comment]
> > https://plugins.jetbrains.com/plugin/19316-rancher/versions/stable/356632 已发布
> 
> ![image](https://user-images.githubusercontent.com/30413147/251324235-d5b8f05d-9f7f-4611-9b7d-cdb151818c07.png) 地址配置成功，但是打开失败了，我的kubectl是使用docker for desktop启用k8s安装上的，不知道是不是和这个有关系

按提示，将kubectl可执行路径配置到环境变量中试试

**Comment by HaloTT** [comment]
![image](https://github.com/threefish/Rancher-plugins/assets/30413147/1e178350-f126-4492-9fda-124203b0a604)
![image](https://github.com/threefish/Rancher-plugins/assets/30413147/80b01b54-7b64-4cb8-bcc5-beca084ad9cc)
path指向的是个替身，不知道是不是和这个有关，但是我将docker下的真实可执行文件的父文件夹加入path中依旧报错

**Comment by threefish** [comment]
我会修复它的，再稍等几天

**Comment by threefish** [comment]
1、下载 https://dl.k8s.io/release/v1.27.3/bin/darwin/arm64/kubectl 将其保存到 $PATH 目录下（终端中执行可查看对应目录：echo $PATH）
2、在https://github.com/rancher/cli/releases   下载页面中下载对应的rancher可执行文件，同样将其保存到 $PATH 目录下
3、在终端中执行  rancher -v  或 kubectl version 查看效果。
4、在idea插件配置中去掉可执行目录配置，再点检测按钮试试

PS：以上我在linux环境和Windows环境下测试通过。

**Comment by HaloTT** [comment]
<img width="441" alt="image" src="https://github.com/threefish/Rancher-plugins/assets/30413147/04867a72-d073-4162-b59e-900f7977bcbe">
可以配置成功了，也能连接上了，但是打开时只有一个默认的group,随便点开一个pod查看日志，下面的terminal一闪而过，看不到内容，其他的也都无法使用

**Comment by HaloTT** [comment]
> <img alt="image" width="441" src="https://user-images.githubusercontent.com/30413147/252292164-04867a72-d073-4162-b59e-900f7977bcbe.png"> 可以配置成功了，也能连接上了，但是打开时只有一个默认的group,随便点开一个pod查看日志，下面的terminal一闪而过，看不到内容，其他的也都无法使用

![image](https://github.com/threefish/Rancher-plugins/assets/30413147/15d6c0ca-792e-4205-85f0-8d63a298f7c3)一闪而过的终端，截到了，出现提示后就切到local tab了

**Comment by threefish** [comment]
macos的虚拟机中测试没遇到图上的问题。但是我未使用homebrew。下面是我的安装方式。

**Comment by threefish** [comment]
macos 请按照下面的命令进行尝试。
```
mkdir -p /usr/local/bin
cd /usr/local/bin
# Add /usr/local/bin to the path ，you can see https://stackoverflow.com/questions/11025980/how-to-add-usr-local-bin-in-path-on-mac

# 删除旧文件，请自己备份.Delete old files and back them up yourself
rm -rf  rancher
rm -rf  kubectl


curl -LO https://github.com/rancher/cli/releases/download/v2.6.11/rancher-darwin-amd64-v2.6.11.tar.gz
tar zxvf rancher-darwin-amd64-v2.6.11.tar.gz
cp rancher-v2.6.11/rancher ./
rm -rf rancher-darwin-amd64-v2.6.11.tar.gz

##  for MACOS intel CPU
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/darwin/amd64/kubectl"
## for Apple Silicon CPU
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/darwin/arm64/kubectl"

## 重启一下
reboot
```

如果还不行就需要在/usr/bin 下执行才行。原因是idea启动后丢失了PATH中缺失了/usr/local/bin这个环境变量。

**Comment by threefish** [comment]
我重构了底层交互逻辑，不依赖rancher-cli了。文件上传下载还未实现。再稍晚几天发布。

**Comment by threefish** [comment]
插件已上传
