### ISSUE TITLE
购买了licenses，一点右下角区域的东西，就会跳出licenses

### ISSUE THREAD

**Issue by 153103242** [threefish/Rancher-plugins#2]
![image](https://github.com/user-attachments/assets/ebdc097e-1036-4d2f-8701-ffb890704a81)

**Comment by 153103242** [comment]
2023.7.23版本

**Comment by threefish** [comment]
不好意思，给您造成麻烦了，冒昧问您的idea是正版吗？如果不是，则会出现以上情况。如果是，则可能是误判，我需要更多信息来改进。

**Comment by threefish** [comment]
> 2023.7.23版本

加我微信： purpleyuxiao
